### ISSUE TITLE
Sporadic failure in Safe Contracts repo

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#287]
**Steps to reproduce:**

1. Check out https://github.com/safe-global/safe-smart-account at the latest master branch
1. Check out https://github.com/NomicFoundation/hardhat/tree/edr/fix/cache-block-contexts
1. Change the hardhat dependency to latest `hardat-core` version in the branch
1. Set export `HARDHAT_EXPERIMENTAL_VM_MODE=edr`
1. Run `npx hardhat test --grep "Migration library"`

**Expected result**

The test passes.

**Actual result**

The tests sometimes fail with

```
1) Safe150Migration library
       migrateWithSetGuardAndFallbackHandler
         can unset an incompatible guard during the migration:
     Error: VM Exception while processing transaction: reverted with reason string 'GS013'
    at <UnrecognizedContract>.<unknown> (0xf1ff1ed140d68c6883f897718b1f4a07e55abb25)
    at SafeProxy.<fallback> (contracts/proxies/SafeProxy.sol:43)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:609:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:299:20)
    at async Proxy.execTransaction (node_modules/ethers/src.ts/contract/contract.ts:338:16)
    at async Context.<anonymous> (test/libraries/Safe150Migration.spec.ts:681:13)


  2) Safe150Migration library
       migrateL2WithSetGuardAndFallbackHandler
         can unset an incompatible guard during the migration:
     Error: VM Exception while processing transaction: reverted with reason string 'GS013'
    at <UnrecognizedContract>.<unknown> (0x26a1609269b31710e474424866f62de6112a6fd3)
    at SafeProxy.<fallback> (contracts/proxies/SafeProxy.sol:43)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:609:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:299:20)
    at async Proxy.execTransaction (node_modules/ethers/src.ts/contract/contract.ts:338:16)
    at async Context.<anonymous> (test/libraries/Safe150Migration.spec.ts:816:13)
```

**Definition of done**

`for run in {1..100}; do npx hardhat test || exit 1; done` passes in the [branch.](https://github.com/NomicFoundation/hardhat/tree/edr/fix/cache-block-contexts)

**Comment by agostbiro** [comment]
Fixed by https://github.com/NomicFoundation/hardhat/pull/4815/commits/015e31f9b949f4e0325ec471b22500fd4672986e
